FROM ghcr.io/suwayomi/suwayomi-server:latest
ENV TZ=Asia/Kolkata
ENV SERVER_IP=0.0.0.0
ENV SERVER_PORT=4567
ENV SYSTEM_USER_AGENT="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
EXPOSE 4567